format=1
abi=arm64-v8a
coreVersion=2
bootstrapUrl=https://github.com/termux/termux-packages/releases/download/bootstrap-2026.08.30-r1%2Bapt.android-7/bootstrap-aarch64.zip
bootstrapSha256=7e92f4c435d16207cdda63d5629e666ab98441f09eefa6a8423037ef13263346
corePackages=ca-certificates,ca-certificates-java,resolv-conf,openjdk-17,aapt,aapt2,aidl
