plugins {
    id 'com.android.application'
}

android {
    namespace 'com.longdev.apkbuilder'
    compileSdk 37
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.apkbld'
        minSdk 30
        targetSdk 31
        versionCode 35
        versionName '35'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
